name: nest_app
description: "NEST Hamburg App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  intl: ^0.18.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.3
  table_calendar: ^3.0.9
  flutter_stripe: ^12.2.0
  http: ^1.1.0 # <-- We need this for the backend calls to Stripe API
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png
    - assets/images/onboarding_4.png
    - assets/images/onboarding_5.png
    - assets/images/nest_logo.png
    - assets/images/delia and melissa.jpeg
    - .env

  fonts:
    - family: SweetAndSalty
      fonts:
        - asset: assets/fonts/Sweet&Salty-Regular.otf

    - family: CharlevoixPro
      fonts:
        - asset: assets/fonts/CharlevoixPro-Thin.otf
          weight: 100
        - asset: assets/fonts/CharlevoixPro-Light.otf
          weight: 300
        - asset: assets/fonts/CharlevoixPro-Regular.otf
          weight: 400
        - asset: assets/fonts/CharlevoixPro-Medium.otf
          weight: 500
        - asset: assets/fonts/CharlevoixPro-Bold.otf
          weight: 700
        - asset: assets/fonts/CharlevoixPro-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/CharlevoixPro-Black.otf
          weight: 900


