name: nest_app
description: "NEST Hamburg App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  intl: ^0.18.1
  flutter_dotenv: ^6.0.0
  table_calendar: ^3.0.9
  flutter_stripe: ^12.2.0
  http: ^1.1.0 # <-- We need this for the backend calls to Stripe API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png
    - assets/images/onboarding_4.png
    - assets/images/onboarding_5.png
    - assets/images/nest_logo.png
    - assets/images/carousel_full.png
    - assets/images/carousel_regular.png
    - assets/images/carousel_parttime.png
    - assets/images/carousel_light.png
    - assets/images/carousel_flexi.png
    - assets/images/carousel_day.png
    - .env
